# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UseDotNet@2
  displayName: "Use .NET 7.x"
  inputs:
    packageType: 'sdk'
    version: '7.x'

- script: |
    dotnet publish SeaweedFs.Gui/SeaweedFS.Gui.Desktop/SeaweedFS.Gui.Desktop.csproj -a x64 --os win -c Release
  displayName: "Publish"

- task: CopyFiles@2
  displayName: "Copy published files to artifact staging directory"
  inputs:
    SourceFolder: '$(agent.builddirectory)\**\publish\**'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'

